services:
  parser:
    image: securities-parser:latest
    build: .
    volumes:
      - ./input:/input
      - ./output:/output
    environment:
      SHEET: "Securities"
      SKIPROWS: "2"
      AMOUNT_COLUMNS: "col10,col8,col12,col11,col14,col15"
      PATTERN: "*.xlsx"